# Generated by Django 6.1.1 on 2026-09-22 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 9, 22, 11, 20, 13, 27180, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
