# Generated by Django 6.1.1 on 2026-09-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodspot_app', '0003_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
