# Generated by Django 6.1.1 on 2026-09-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='imgage',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
    ]
